Repository thariyarox/CoinSpot-Data-Crawler, pull requests merged in 2020-10, with the labels that each got.

#1 Adding project requirements into the readme file
  README.md
Labels: Hacktoberfest

#2 Adding contributing file for Hacktoberfest
  CONTRIBUTING.md
Labels: Hacktoberfest

#4 Create spider to crawl coinspot
  .gitignore
  crawler/__init__.py
  crawler/items.py
  crawler/middlewares.py
  crawler/pipelines.py
  crawler/settings.py
  crawler/spiders/__init__.py
  crawler/spiders/coinspot.py
  scrapy.cfg
Labels: hacktoberfest-accepted

#5 Add instructions for installing and running the scripts
  README.md
  requirements.txt
Labels: Hacktoberfest, hacktoberfest-accepted

#7 added the pipeline for adding data to the text file
  README.md
  crawler/pipelines.py
  crawler/settings.py
Labels: Hacktoberfest, hacktoberfest-accepted

#9 added the script to add data to csv file
  crawler/run.py
Labels: Hacktoberfest, hacktoberfest-accepted

#12 Fixing issue when running the pipeline
  crawler/settings.py
Labels: Hacktoberfest, hacktoberfest-accepted

#15 Processing csv data file to create another csv file in same folder
  data/stats.csv
  processors/README.md
  processors/process_csv.py
  processors/requirements.txt
  processors/screenshot.png
Labels: Hacktoberfest, hacktoberfest-accepted

#19 Fixes Type Error and added relative path for the files
  crawler/run.py
  processors/process_csv.py
Labels: Hacktoberfest, hacktoberfest-accepted
